name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  DATABASE_URL: postgres://andela@127.0.0.1:5432/dutydb
  ME: andela
  DB_NAME: dutydb
  TOKEN: secret
jobs:

  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: pextech/dutygen:lastest
        env:
          POSTGRES_PASSWORD: postgres
          ME: andela
          DB_NAME: dutydb
          TOKEN: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run migrate
    - run: npm test