---
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with: 
          node-version: "${{ matrix.node-version }}"
      - 
        run: "npm ci"
      - 
        run: "npm run build --if-present"
      - 
        run: "npm test"
      - 
        env: 
          DB_NAME: "${{secrets.DB_NAME}"
          DB_PORT: "${{secrets.DB_PORT}"
          DIALECT: "${{secrets.DIALECT}"
          HOST: "${{secrets.HOST}"
          ME: "${{secrets.ME}"
          NODE_AUTH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
        run: "npm run cover"
    strategy: 
      matrix: 
        node-version: 
          - 10.x
          - 12.x
          - 14.x
name: "Node.js CI"
true: 
  pull_request: 
    branches: 
      - develop
  push: 
    branches: 
      - develop
